export const FETCH_GAME = "FETCH_GAME";
export const FETCH_GAME_BY_ID = "FETCH_GAME_BY_ID";
export const FETCH_GAME_BY_ID_SUCCESS = "FETCH_GAME_BY_ID_SUCCESS";
export const REMOVE_GAME = "REMOVE_GAME";
export const ID_FETCH_URL = "https://www.boardgamegeek.com/xmlapi2/thing?id=";
export const ROOT_URL = "https://www.boardgamegeek.com/xmlapi2/search?&exact=1&query=";
export const BACK_ARROW_IMG = "https://image.flaticon.com/icons/png/512/60/60577.png";
export const REMOVE_GAME_IMG = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHvQzPD7lYrTQvIywYogS50koNq25j2A3K7Q&usqp=CAU";
export const MAG_GLASS_IMG = "https://static.thenounproject.com/png/340642-200.png";